name: Matador Capital Group
favicon: null
layout_spectrum: 0.883401483297348
typography_spectrum: 0.8383652959018946
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9395932254847139
  lightness: 0.04653273173607886
  saturation: 0.08708833600394428
  rhythmicContrast: 0.09962819376960397
purpose: []
